name: Build Termux Package

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y git clang python3-pip wget

      - name: Set up Termux build environment
        run: |
          git clone https://github.com/termux/termux-packages.git
          cd termux-packages
          ./scripts/setup-ubuntu.sh

      - name: Build package
        run: |
          cd termux-packages/packages/<package-name>
          ./build-package.sh -a aarch64 -f termux-tools

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-packages
          path: termux-packages/debs/*.deb