name: Build Termux Package

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - 'properties.sh'
      - 'setup-*.sh'
      - 'build/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -t ghcr.io/termux/package-builder .

    - name: Run Build Script in Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/home/builder/termux-packages ghcr.io/termux/package-builder \
        /tmp/build/termux_download.sh

    - name: Archive Build Output
      run: mkdir -p build-output && cp -r /home/builder/termux-packages/build/outputs/* build-output/

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: termux-build-artifacts
        path: build-output/
